/*
 * This file is auto-generated by simulator_c.ml.
 * Do not modify it directly!
 */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>
#include <string.h>

#include "memory.h"

const unsigned long long nbSteps = 0xFFFFFFFFFF;

/** Returns true if @a s ends with @a t (equivalently if @a t is a suffix of @a s). */
static int strendswith(const char *s, const char *t)
{
    size_t slen = strlen(s);
    size_t tlen = strlen(t);
    if (tlen > slen)
        return 1;
    return strcmp(s + slen - tlen, t);
}

int main(int argc, char *argv[])
{
    size_t ram_file_count = 0, rom_file_count = 0;
    const char **ram_files = malloc(sizeof(const char *) * (argc - 1));
    const char **rom_files = malloc(sizeof(const char *) * (argc - 1));
    check_alloc(ram_files);
    check_alloc(rom_files);
    for (int i = 1; i < argc; ++i)
    {
        if (argv[i][0] != '-')
        {
            if (strendswith(argv[i], ".do") || strendswith(argv[i], ".ram") || strendswith(argv[i], ".data"))
            {
                ram_files[ram_file_count++] = argv[i];
            }
            else if (strendswith(argv[i], ".po") || strendswith(argv[i], ".rom") || strendswith(argv[i], ".code"))
            {
                rom_files[rom_file_count++] = argv[i];
            }
            else
            {
                fprintf(stderr, "error: unknown type for file '%s'\n", argv[i]);
            }
        }
        else
        {
            fprintf(stderr, "error: unknown option '%s'\n", argv[i]);
        }
    }

    free(ram_files);
    free(rom_files);

    for (unsigned long long iStep = 0; iStep != nbSteps; iStep++)
    {
        printf("Step %lld:\n", iStep + 1);
        $CYCLE$
    }
}